# In order to run this, you must do 2 things:
# 1. docker pull --platform linux/amd64 ghcr.io/foundry-rs/foundry:latest
# 2. docker build --platform linux/amd64 -t fossil-header-anvil -f Dockerfile.anvil . 
# This ensures you can successfully locate and build the image.
FROM ghcr.io/foundry-rs/foundry:latest

WORKDIR /anvil

# ENTRYPOINT anvil --fork-url $FORK_URL --host 0.0.0.0
ENTRYPOINT anvil --host 0.0.0.0
